### ISSUE TITLE
Add ability to record audio

### ISSUE THREAD

**Issue by IgnusG** [manateelazycat/deepin-screen-recorder#5]
I think this one doesn't record audio.
Would it be possible to add such functionality?

**Comment by LeBaux** [comment]
Seconding the audio — it would greatly improve the build in recorder, mitigating the need to install another, 3rd. party recorder. What are your thoughts @manateelazycat? Thanks!

**Comment by manateelazycat** [comment]
@LeBaux Thanks for patch, i have leave from deepin, you can send PR to https://github.com/linuxdeepin/deepin-screen-recorder/
